dist: trusty
language: php
sudo: required
os:
  - linux

jobs:
  include:
    - php: 7.4
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update
  - composer --version
  - php --version

install:
  - composer update --no-interaction --no-progress

script:
  - php vendor/bin/phpunit

after_script:
  - composer code:coverage
