dist: trusty
language: php
sudo: required
os:
  - linux

jobs:
  include:
    - php: nightly
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - composer install

script:
  - php vendor/bin/phpunit

after_script:
  - composer code:coverage
