name: "mutation tests"

on: ["pull_request", "push"]

jobs:
  unit-tests:
    name: "mutation tests"

    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v2"

      - name: "installing PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "7.4"
          ini-values: memory_limit=-1
          tools: composer:v2, cs2pr

      - name: "installing dependencies"
        run: "composer update --no-interaction --no-progress"

      - name: "running mutation tests ( infection )"
        run: "./vendor/bin/infection"
        env:
          INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
