name: "static analysis"

on: ["pull_request", "push"]

jobs:
  static-analysis:
    name: "static analysis"
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v2"

      - name: "installing PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.0"
          ini-values: memory_limit=-1
          tools: composer:v2, cs2pr

      - name: "installing dependencies"
        run: "composer update --no-interaction --no-progress --ignore-platform-req php"

      - name: "running static analysis ( psalm )"
        run: "php vendor/bin/psalm  --output-format=github --shepherd --stats"
